apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend   # Ensure that this matches the labels in the Pod template
  template:
    metadata:
      labels:
        app: frontend   # Specify the same labels as in the selector
    spec:
      containers:
      - name: frontend-container
        image: subhasish09/flask:0.1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer # You can use NodePort for testing purposes, adjust as needed

